version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ./databases/postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql